name = "edge-gateway"
main = "index.ts"
compatibility_date = "2024-04-01"

[vars]
UPSTASH_REDIS_REST_URL = "https://resolved-flounder-82948.upstash.io"
UPSTASH_REDIS_REST_TOKEN = "gQAAAAAAAUQEAAIgcDE1NmY5NWQ4MmVlMjY0NDY4ODc4NTEzNzdjNDI0ZTBlMg"


[observability]
enabled = true
